dist: focal  # используем Ubuntu 20.04
sudo: required  # испоьлзуем Virtual Machine

language: c
os: linux
compiler: gcc

install:
  # cmake, clang-form, valgrind
  - sudo apt update
  - sudo apt install clang-format
  - sudo apt install valgrind
  - sudo apt install cmake
  # GTest
  - sudo apt install libgtest-dev
  - sudo apt install cppcheck
  # configure after installation
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo apt-get install cppcheck
  - sudo apt-get -qq update
  - sudo apt-get install -y libgtest-dev valgrind cmake
  - sudo wget https://github.com/google/googletest/archive/release-1.7.0.tar.gz
  - sudo tar xf release-1.7.0.tar.gz
  - cd googletest-release-1.7.0
  - sudo cmake -DBUILD_SHARED_LIBS=ON .
  - sudo make
  - sudo cp -a include/gtest /usr/include
  - sudo cp -a libgtest_main.so libgtest.so /usr/lib/
  - which valgrind
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cppcheck source_lib/main.c source_lib/input_output.c source_lib/input_output.h source_lib/logic.c source_lib/logic.h
  - mkdir build
  - cd build
  - ls
  - cmake
  - cd ../Google_tests
  - ls
  - valgrind --tool=memcheck --leak-check=full --show-leak-kinds=all --leak-resolution=med  --track-origins=yes chmod a+x ./tests.cpp
  - chmod a+x ./tests.cpp
  -cd ../cmake-build-debug
 



after_script:
  bash <(curl -s https://codecov.io/bash) -t 4045668d-56cd-4fcd-b3a8-a40ddf8f6258